[package]
name = "digiphoto"
version = "0.1.0"
authors = ["Yuki MIZUNO <mizuyuu0904@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.8"

[build-dependencies]
bindgen = "0.58.1"
cc = "1.0.67"
